### ISSUE TITLE
Update users for an HTPasswd identity provider

### ISSUE THREAD

**Issue by tchnmf** [tchnmf/ocp-config#1]
https://docs.openshift.com/container-platform/4.8/authentication/identity_providers/configuring-htpasswd-identity-provider.html

Replace the htpass-secret Secret object with the updated users in the users.htpasswd file:

```
$ oc create secret generic htpass-secret --from-file=htpasswd=users.htpasswd --dry-run=client -o yaml -n openshift-config | oc replace -f -
```

Or  apply the following YAML to replace the secret. 
The block is declared in [oauth.yml](https://github.com/tchnmf/ocp-config/blob/main/auth/oauth.yml)
```
apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: <base64_encoded_htpasswd_file_contents>
```
